version: '3'

services:
  processtext-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: processtext_service
    command: bash -c "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:9000"
    ports:
      - 9876:9000
    restart: unless-stopped
